### ISSUE TITLE
Other TODO list

### ISSUE THREAD

**Issue by miccio-dk** [Christie22/SingleChannelDenoising#4]
A. [ ] Appendix
   1. [ ] Attachment structure
   2. [ ] Models graphs & params
   3. [ ] ...
B. [ ] Other Report
    1. [ ] Figures
    2. [ ] Attachment
        1. [ ] Source code
        2. [ ] Audio samples (test, train, etc)
        3. [ ] `README.md`s
        4. [ ] TensorBoard logs
        5. [ ] Training JSON logs
        6. [ ] ...
C. [ ] Video
    1. [x] Idea
    2. [ ] Script
    3. [ ] Recording
    4. [ ] Other material (predicted audio, screencasts)
    5. [ ] Edit

**Comment by miccio-dk** [comment]
video timeline https://gist.github.com/miccio-dk/f6ec680b0ad0c8a61c45079bcc9fd65a
